package com.gentoro.onemcp.handbook.model.agent;

import java.time.format.DateTimeFormatter;

public class Release {

  private String version;
  private Author author;
  private String date;
  private String description;

  public Release() {
    version = "0.0.1";
    description = "Initial release auto-generated by OneMCP";
    date = DateTimeFormatter.ofPattern("yyyy-MM-dd").format(java.time.LocalDateTime.now());
    author = new Author();
  }

  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Author getAuthor() {
    return author;
  }

  public void setAuthor(Author author) {
    this.author = author;
  }

  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }
}
